#!/bin/sh

# echo "$@"
if test -z "$JENKINS_URL"; then
  echo "JENKINS_URL environment variable is mandatory"
  exit 1
else

  cli_jar="/opt/src/jenkins-cli.jar"
  if [ -f "$PRIVATE_KEY" ]; then
    java -jar "$cli_jar" -s $JENKINS_URL -i $PRIVATE_KEY "$@"
  else
    java -jar "$cli_jar" -s $JENKINS_URL "$@"
  fi
fi